<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <AssemblyName>FFTestMod</AssemblyName>
        <Product>FFTestMod</Product>
        <Version>1.0.0</Version>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>latest</LangVersion>
        <RestoreAdditionalProjectSources>
            https://api.nuget.org/v3/index.json;
            https://nuget.bepinex.dev/v3/index.json;
            https://nuget.samboy.dev/v3/index.json
        </RestoreAdditionalProjectSources>
        <RootNamespace>FFTestMod</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all"/>
        <PackageReference Include="BepInEx.Core" Version="5.*"/>
        <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*"/>
        <PackageReference Include="UnityEngine.Modules" Version="6000.3.17" IncludeAssets="compile"/>
    </ItemGroup>

    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="Assembly-CSharp">
            <HintPath>lib/Assembly-CSharp.dll</HintPath>
        </Reference>
        <Reference Include="Assembly-CSharp-firstpass">
            <HintPath>lib/Assembly-CSharp-firstpass.dll</HintPath>
        </Reference>
        <Reference Include="Data">
            <HintPath>lib/Data.dll</HintPath>
        </Reference>
        <Reference Include="ZLinq">
            <HintPath>lib/ZLinq.dll</HintPath>
        </Reference>
        <Reference Include="UniTask">
            <HintPath>lib/UniTask.dll</HintPath>
        </Reference>
        <Reference Include="PrimeTweeen.Runtime">
            <HintPath>lib/PrimeTweeen.Runtime.dll</HintPath>
        </Reference>
    </ItemGroup>
</Project>
